import { SkillRegistry } from '@/core/SkillRegistry.js';
import { ANGULAR_STANDALONE_MODERN_SKILL, ANGULAR_TYPED_FORMS_SKILL } from './angularSkills.js';
import {
  API_ERRORS_RESILIENCE_SKILL,
  DESIGN_TOKENS_STATES_SKILL,
  HEXAGONAL_NESTJS_SKILL,
  OWASP_API_TOP10_SKILL,
  WCAG_FORMS_SKILL,
} from './backendUxSkills.js';
import {
  ANGULAR_SIGNALS_SKILL,
  CORE_WEB_VITALS_SKILL,
  REACT_SERVER_FIRST_SKILL,
} from './frontendSkills.js';
import { PCI_DSS_SKILL, RICE_SKILL, WSJF_SKILL } from './productSkills.js';
import {
  NEXT_INTL_COOKIE_SKILL,
  NEXT_SERVER_COOKIES_SKILL,
  REACT_HOOK_FORM_ZOD_SKILL,
  ZUSTAND_PERSIST_SKILL,
} from './reactStackSkills.js';

/**
 * Registro global de skills compartido por todos los agentes.
 * Los agentes lo reciben por defecto; los tests pueden inyectar uno propio.
 */
export const skillRegistry = new SkillRegistry()
  .register(PCI_DSS_SKILL)
  .register(WSJF_SKILL)
  .register(RICE_SKILL)
  .register(CORE_WEB_VITALS_SKILL)
  .register(REACT_SERVER_FIRST_SKILL)
  .register(ANGULAR_SIGNALS_SKILL)
  .register(ANGULAR_STANDALONE_MODERN_SKILL)
  .register(ANGULAR_TYPED_FORMS_SKILL)
  .register(HEXAGONAL_NESTJS_SKILL)
  .register(OWASP_API_TOP10_SKILL)
  .register(API_ERRORS_RESILIENCE_SKILL)
  .register(WCAG_FORMS_SKILL)
  .register(DESIGN_TOKENS_STATES_SKILL)
  .register(REACT_HOOK_FORM_ZOD_SKILL)
  .register(ZUSTAND_PERSIST_SKILL)
  .register(NEXT_INTL_COOKIE_SKILL)
  .register(NEXT_SERVER_COOKIES_SKILL);

export {
  ANGULAR_SIGNALS_SKILL,
  ANGULAR_STANDALONE_MODERN_SKILL,
  ANGULAR_TYPED_FORMS_SKILL,
  API_ERRORS_RESILIENCE_SKILL,
  CORE_WEB_VITALS_SKILL,
  DESIGN_TOKENS_STATES_SKILL,
  HEXAGONAL_NESTJS_SKILL,
  NEXT_INTL_COOKIE_SKILL,
  NEXT_SERVER_COOKIES_SKILL,
  OWASP_API_TOP10_SKILL,
  PCI_DSS_SKILL,
  REACT_HOOK_FORM_ZOD_SKILL,
  REACT_SERVER_FIRST_SKILL,
  RICE_SKILL,
  WCAG_FORMS_SKILL,
  WSJF_SKILL,
  ZUSTAND_PERSIST_SKILL,
};
